# syntax=docker/dockerfile:1
FROM php:8.2-cli
ENV COMPOSER_ALLOW_SUPERUSER=1 APP_ENV=prod

RUN apt-get update \
 && apt-get install -y git unzip libzip-dev \
 && docker-php-ext-install pdo_mysql zip opcache \
 && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
WORKDIR /app
COPY . .
RUN composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

EXPOSE 10000
CMD ["php","-S","0.0.0.0:10000","-t","public","public/index.php"]
